# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20170106_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.Response'),
        ),
    ]
