# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20170106_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('SELECT ONE', 'Select one'), ('SELECT MULTIPLE', 'Select multiple'), ('INTEGER', 'Integer')], default='TEXT', max_length=50),
        ),
    ]
