# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20170106_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='response_id',
            new_name='responder_id',
        ),
    ]
