# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20161229_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
